# Generated by Django 2.2.19 on 2022-10-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20221029_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favorite_count',
            field=models.IntegerField(default=0, verbose_name='Число добавлений рецепта в избранное'),
        ),
    ]
